# Generated by Django 2.2.2 on 2020-05-15 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(max_length=2000, verbose_name='Описание')),
                ('is_done', models.BooleanField(default=False, verbose_name='Сделано')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('deadline', models.DateTimeField(default=datetime.datetime(2020, 5, 16, 20, 50, 25, 793584), verbose_name='Дата дедлайна')),
            ],
        ),
    ]
