# Generated by Django 2.2.2 on 2020-05-15 18:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todosapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todos',
            old_name='name',
            new_name='name_of_todo',
        ),
        migrations.AlterField(
            model_name='todos',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 16, 21, 4, 53, 909823), verbose_name='Дата дедлайна'),
        ),
    ]
