# Generated by Django 2.2.2 on 2020-05-17 12:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todosapp', '0002_auto_20200515_2104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todos',
            options={'ordering': ('-date', 'is_done')},
        ),
        migrations.AddField(
            model_name='todos',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='автор'),
        ),
        migrations.AlterField(
            model_name='todos',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 18, 15, 20, 42, 681696), verbose_name='Дата дедлайна'),
        ),
    ]
